# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #NXOSv 9 version #1
  config.vm.define "nxosv251" do |cfg|
     cfg.vm.box = "sysnet4admin/nxosv_v9"
     cfg.ssh.insert_key = false 
     cfg.vm.boot_timeout = 960
     cfg.vm.guest = :openbsd
     cfg.vm.base_mac = "F000F251F000"
     #cfg.vbguest.auto_update = false
     cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
     cfg.vm.network "forwarded_port", guest: 22, host: 60251, auto_correct: true, id: "ssh"
     cfg.vm.network "private_network", virtualbox__intnet: "eth1/1", auto_config: false
     cfg.vm.network "private_network", virtualbox__intnet: "eth1/2", auto_config: false
     cfg.vm.network "private_network", virtualbox__intnet: "eth1/3", auto_config: false

     if VAGRANT_COMMAND = "up"
       cfg.ssh.username = "admin"
       cfg.ssh.password = "vagrant"
       cfg.ssh.shell = "conf t ; switchname nxosv251"
    end
 
     #VM name & HW config
     cfg.vm.provider "virtualbox" do |vb|
       vb.name = "NXOSv251(github_SysNet4Admin)"
       vb.customize ["modifyvm", :id, "--groups", "/NX-OSv_Automation(github-SysNet4Admin)"]
       vb.memory = 6144
	   vb.customize ["modifyvm", :id, "--uart1", "0x251", "1"]
       vb.customize ["modifyvm", :id, "--uartmode1", "server", '\\\.\pipe\nxosv251']
       vb.customize ['modifyvm', :id,'--nicpromisc2','allow-all']
       vb.customize ['modifyvm', :id,'--nicpromisc3','allow-all']
       vb.customize ['modifyvm', :id,'--nicpromisc4','allow-all']
     end 
  end
  
  #NXOSv 7 version #1
  config.vm.define "nxosv252" do |cfg|
     cfg.vm.box = "sysnet4admin/nxosv_v7"
     cfg.ssh.insert_key = false 
     cfg.vm.boot_timeout = 960
     cfg.vm.guest = :openbsd
     cfg.vm.base_mac = "F000F252F000"
     #cfg.vbguest.auto_update = false
     cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
     cfg.vm.network "forwarded_port", guest: 22, host: 60252, auto_correct: true, id: "ssh"
     cfg.vm.network "private_network", virtualbox__intnet: "eth1/1", auto_config: false
     cfg.vm.network "private_network", virtualbox__intnet: "eth1/2", auto_config: false
     cfg.vm.network "private_network", virtualbox__intnet: "eth1/3", auto_config: false

     if VAGRANT_COMMAND = "up"
       cfg.ssh.username = "admin"
       cfg.ssh.password = "vagrant"
       cfg.ssh.shell = "conf t ; switchname nxosv252"
    end     
     
     #VM name & HW config
     cfg.vm.provider "virtualbox" do |vb|
       vb.name = "NXOSv252(github_SysNet4Admin)"
       vb.customize ["modifyvm", :id, "--groups", "/NX-OSv_Automation(github-SysNet4Admin)"]
       vb.memory = 4096
       vb.customize ["modifyvm", :id, "--uartmode1", "server", '\\\.\pipe\nxosv252']
       vb.customize ['modifyvm', :id,'--nicpromisc2','allow-all']
       vb.customize ['modifyvm', :id,'--nicpromisc3','allow-all']
       vb.customize ['modifyvm', :id,'--nicpromisc4','allow-all']
     end 
  end
    
  
end